find_path(FONTCONFIG_INCLUDE_DIR fontconfig/fontconfig.h)
find_library(FONTCONFIG_LIBRARY NAMES fontconfig)
if(FONTCONFIG_LIBRARY AND FONTCONFIG_INCLUDE_DIR)
  set(FONTCONFIG_FOUND TRUE)
endif(FONTCONFIG_LIBRARY AND FONTCONFIG_INCLUDE_DIR)
mark_as_advanced(FONTCONFIG_INCLUDE_DIR FONTCONFIG_LIBRARY)

